/**
 * TaskForm Component
 * 
 * This is the form dialog for creating and editing tasks.
 * It's a "smart" form that works for both adding new tasks and editing existing ones.
 * 
 * How it works:
 * - When opened for editing, it pre-fills with the task's current data
 * - When opened for creating, it starts with empty fields
 * - Uses animated inputs for a polished user experience
 * - Validates that title is required before submission
 * 
 * The form is displayed in a modal dialog that overlays the page.
 */

import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog';

import { Button } from '@/components/ui/button';
import { AnimatedInput } from '@/components/ui/animated-input';
import { Textarea } from '@/components/ui/textarea';
import { Dropdown } from '@/components/ui/dropdown';
import type { Task } from '@/services/taskService';

/**
 * TaskFormData Interface
 * 
 * This defines what data the form collects from the user.
 * Note: This doesn't include id, completed, or createdAt because
 * those are auto-generated by the service layer.
 */
export interface TaskFormData {
  title: string;                    // Required: task name
  description: string;              // Optional: detailed description
  dueDate: string;                  // Optional: when the task is due (ISO date string)
  priority: 'low' | 'medium' | 'high';  // Required: priority level
}

interface TaskFormProps {
  isOpen: boolean;                  // Whether the dialog is visible
  onClose: () => void;              // Called when user closes the dialog
  onSubmit: (formData: TaskFormData) => void;  // Called when form is submitted
  task?: Task | null;               // If provided, we're editing this task. If null, we're creating new.
}

const TaskForm: React.FC<TaskFormProps> = ({ isOpen, onClose, onSubmit, task }) => {
  // State to hold the form data as user types
  // This is the "local" state of the form inputs
  const [formData, setFormData] = useState<TaskFormData>({
    title: '',
    description: '',
    dueDate: '',
    priority: 'medium'  // Default to medium priority
  });

  /**
   * When the dialog opens or the task prop changes, update the form data.
   * 
   * This effect runs whenever:
   * - The dialog opens/closes (isOpen changes)
   * - A different task is being edited (task prop changes)
   * 
   * If we're editing (task is provided), pre-fill the form with that task's data.
   * If we're creating (task is null), reset the form to empty/default values.
   */
  useEffect(() => {
    // Only update form data when dialog is open
    if (isOpen) {
      if (task) {
        // We're editing an existing task - pre-fill the form
        setFormData({
          title: task.title,
          description: task.description || '',      // Use empty string if no description
          dueDate: task.dueDate || '',              // Use empty string if no due date
          priority: task.priority
        });
      } else {
        // We're creating a new task - start with empty form
        setFormData({
          title: '',
          description: '',
          dueDate: '',
          priority: 'medium'
        });
      }
    }
  }, [isOpen, task]);  // Re-run when dialog opens/closes or task changes

  /**
   * Handle changes to any form input field
   * 
   * This is called whenever user types in any input field.
   * We update the formData state with the new value, which causes
   * React to re-render the input with the updated value (controlled component).
   * 
   * @param {React.ChangeEvent} e - The change event from the input
   */
  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    // Get the name of the field (e.g., "title", "description") and its new value
    const { name, value } = e.target;
    
    // Update formData by keeping all existing fields and updating just this one
    // The [name] syntax uses the field name as a dynamic property key
    // Example: if name is "title", this becomes { ...prev, title: value }
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  /**
   * Handle form submission
   * 
   * Called when user clicks "Add Task" or "Update Task" button.
   * We validate the form (title is required) and then call the onSubmit callback
   * which will either create or update the task in the parent component.
   * 
   * @param {React.FormEvent} e - The form submit event
   */
  const handleSubmit = (e: React.FormEvent) => {
    // Prevent the default form submission (which would reload the page)
    e.preventDefault();
    
    // Validate: title is required (can't be empty or just whitespace)
    if (!formData.title.trim()) return;  // If no title, don't submit
    
    // Call the parent's onSubmit function with the form data
    // The parent (TasksPage) will handle creating or updating the task
    onSubmit(formData);
    
    // Close the dialog after submission
    onClose();
  };

  /**
   * Handle cancel button click
   * 
   * Called when user clicks "Cancel" or closes the dialog.
   * We reset the form to empty/default values and close the dialog.
   */
  const handleCancel = () => {
    // Reset form to empty/default values
    setFormData({
      title: '',
      description: '',
      dueDate: '',
      priority: 'medium'
    });
    
    // Close the dialog
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="p-8 sm:p-8 sm:max-w-lg max-h-[90vh]">
        <div className="space-y-5 ">
          <DialogHeader className="mb-2 sm:mb-4">
            <DialogTitle className="text-xl font-semibold">
              {task ? 'Edit Task' : 'Add New Task'}
            </DialogTitle>
            <DialogDescription className="text-sm text-muted-foreground">
              {task
                ? 'Update the task details below'
                : 'Fill the information to create a new task'}
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleSubmit} className="space-y-5 sm:space-y-6 pb-2">
            {/* Title */}
            <div className="space-y-2">
              <AnimatedInput
                id="title"
                name="title"
                label="Task Title *"
                value={formData.title}
                onChange={handleChange}
                required
              />
            </div>

            {/* Description */}
            <div className="space-y-2">
              <label
                htmlFor="description"
                className="text-sm font-medium block dark:text-gray-200"
              >
                Description
              </label>
              <Textarea
                id="description"
                name="description"
                placeholder="Enter description (optional)"
                value={formData.description}
                onChange={handleChange}
                rows={4}
                className="resize-none"
              />
            </div>

            {/* Due Date */}
            <div className="space-y-2">
              <AnimatedInput
                id="dueDate"
                name="dueDate"
                type="date"
                label="Due Date"
                value={formData.dueDate}
                onChange={handleChange}
              />
            </div>

            {/* Priority */}
            <div className="space-y-2">
              <label
                htmlFor="priority"
                className="text-sm font-medium block dark:text-gray-200 mb-2"
              >
                Priority
              </label>
              <Dropdown
                options={[
                  { value: 'low', label: 'Low' },
                  { value: 'medium', label: 'Medium' },
                  { value: 'high', label: 'High' },
                ]}
                value={formData.priority}
                onChange={(value) =>
                  setFormData((prev) => ({ ...prev, priority: value as 'low' | 'medium' | 'high' }))
                }
                placeholder="Select priority"
              />
            </div>

            {/* Footer */}
            <DialogFooter className="mt-2 gap-3">
              <Button
                type="button"
                variant="outline"
                onClick={handleCancel}
                className="px-4"
              >
                Cancel
              </Button>
              <Button type="submit" className="px-5">
                {task ? 'Update Task' : 'Add Task'}
              </Button>
            </DialogFooter>
          </form>
        </div>
      </DialogContent>
    </Dialog>
  );
};
export default TaskForm;
